"""initial migration

Revision ID: c56fcbbab896
Revises: 
Create Date: 2026-07-17 11:35:42.959374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56fcbbab896'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bulk_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_tickets', sa.Integer(), nullable=False),
    sa.Column('processed_tickets', sa.Integer(), nullable=False),
    sa.Column('classified_tickets', sa.Integer(), nullable=False),
    sa.Column('unclassified_tickets', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_jobs_id'), 'bulk_jobs', ['id'], unique=False)
    op.create_table('training_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_feedback_id'), 'training_feedback', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('suggested_team', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('bulk_job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bulk_job_id'], ['bulk_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_table('unclassified_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bulk_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bulk_job_id'], ['bulk_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unclassified_tickets_id'), 'unclassified_tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unclassified_tickets_id'), table_name='unclassified_tickets')
    op.drop_table('unclassified_tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_training_feedback_id'), table_name='training_feedback')
    op.drop_table('training_feedback')
    op.drop_index(op.f('ix_bulk_jobs_id'), table_name='bulk_jobs')
    op.drop_table('bulk_jobs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
